name: Build and deploy Github pages
on:
    push:
        branches: [develop]
        paths:
            - "docs/**"
            - "gen-docs.ts"
            - "crates/eww/src/widgets/widget_definitions.rs"
            - "crates/eww/src/config/inbuilt.rs"
            - ".github/workflows/**"

jobs:
    build:
        name: Build mdBook
        runs-on: ubuntu-latest
        steps:
            # Checkout
            - uses: actions/checkout@v4
              with:
                submodules: recursive
                fetch-depth: 0

            # Build widget documentation
            - name: Use deno to build widget documentation
              uses: denoland/setup-deno@main
              with:
                  deno-version: "v1.x"
            - run: deno run --allow-read --allow-write gen-docs.ts ./crates/eww/src/widgets/widget_definitions.rs ./crates/eww/src/config/inbuilt.rs

            # Build & deploy
            - name: build mdBook page
              uses: peaceiris/actions-mdbook@v2
              with:
                  mdbook-version: '0.4.8'
            - run: mdbook build docs

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs/book/
